spring:
  application:
    name: skyeye-user-service

  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    url: jdbc:postgresql://localhost:5432/skyeyedb
    username: romant
    password: 12345678
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      host: redis-cache
      port: 6379
      timeout: 10000ms

  cache:
    type: redis

app:
  db:
    init:
      enabled: true