spring:
  application:
    name: skyeye-user-service
  datasource:
    hikari:
      connectionTimeout: 20000
      maximumPoolSize: 5
    #url: jdbc:postgresql://localhost:5432/skyeyedb
    #username: romant
    #password: 12345678
    url: jdbc:postgresql://sky-eye-db-instance.czu4c2o62jk0.eu-central-1.rds.amazonaws.com:5432/sky_eye_db
    username: admin_user
    password: 9~+LXT3u4;F-dst
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  data:
    redis:
      host: redis-cache
      port: 6379
      timeout: 10000ms

  cache:
    type: redis
server:
  port: 8081
app:
  db:
    init:
      enabled: false